"use client";

import Image from "next/image";
import Link from "next/link";

const buttonStyles = `
  .lpb-btn { transition: all 0.25s cubic-bezier(0.4, 0, 0.2, 1); }
  .lpb-btn:hover { transform: translateY(-2px); }
  .lpb-btn-primary { background: linear-gradient(135deg, #1f766e, #0f5c55); box-shadow: 0 4px 14px rgba(31,118,110,0.4); }
  .lpb-btn-primary:hover { background: linear-gradient(135deg, #238e87, #1a6d65); box-shadow: 0 8px 28px rgba(31,118,110,0.55), 0 0 20px rgba(31,118,110,0.25); }
  .lpb-btn-secondary { border: 1.5px solid rgba(31,118,110,0.35); background: rgba(255,255,255,0.8); }
  .lpb-btn-secondary:hover { background: rgba(31,118,110,0.1); border-color: rgba(31,118,110,0.5); box-shadow: 0 0 20px rgba(31,118,110,0.15); }
  .lpb-btn-dark { border: 1.5px solid rgba(31,118,110,0.45); background: rgba(31,118,110,0.1); }
  .lpb-btn-dark:hover { background: rgba(31,118,110,0.2); box-shadow: 0 0 20px rgba(31,118,110,0.2); }
  .lpb-btn-ghost { color: #4a8a82; }
  .lpb-btn-ghost:hover { color: #1f766e; text-decoration: underline; }
`;
import { useState, useEffect, useRef } from "react";
import {
  ArrowRightIcon,
  type LucideIcon,
  GraduationCapIcon,
  MessagesSquareIcon,
  MoonIcon,
  SparklesIcon,
  SunIcon,
  Users2Icon,
  TrophyIcon,
  BrainCircuitIcon,
  WalletIcon,
  ClockIcon,
  StarIcon,
  CheckCircleIcon,
  ZapIcon,
  VideoIcon,
  ImageIcon,
  FileTextIcon,
  ShieldCheckIcon,
  BarChart3Icon,
  AwardIcon,
  ChevronDownIcon,
  PlayCircleIcon,
  UsersIcon,
  CalendarIcon,
  BookOpenIcon,
  GraduationCap,
} from "lucide-react";
import { useTheme } from "next-themes";

import { getSignInPath, getSignUpPath } from "@/lib/user-paths";

/* ─────────────────────── STYLES ─────────────────────── */
function LandingStyles() {
  return (
    <style>{`
      .lpb-btn { transition: all 0.25s cubic-bezier(0.4, 0, 0.2, 1); }
      .lpb-btn:hover { transform: translateY(-2px); }
      .lpb-btn-primary { background: linear-gradient(135deg, #1f766e, #0f5c55); box-shadow: 0 4px 14px rgba(31,118,110,0.4); }
      .lpb-btn-primary:hover { background: linear-gradient(135deg, #238e87, #1a6d65); box-shadow: 0 8px 28px rgba(31,118,110,0.55), 0 0 20px rgba(31,118,110,0.25); }
      .lpb-btn-secondary { border: 1.5px solid rgba(31,118,110,0.35); background: rgba(255,255,255,0.8); }
      .lpb-btn-secondary:hover { background: rgba(31,118,110,0.1); border-color: rgba(31,118,110,0.5); box-shadow: 0 0 20px rgba(31,118,110,0.15); }
      .lpb-btn-dark { border: 1.5px solid rgba(31,118,110,0.45); background: rgba(31,118,110,0.1); }
      .lpb-btn-dark:hover { background: rgba(31,118,110,0.2); box-shadow: 0 0 20px rgba(31,118,110,0.2); }
      .lpb-btn-ghost { color: #4a8a82; }
      .lpb-btn-ghost:hover { color: #1f766e; text-decoration: underline; }
    `}</style>
  );
}

/* ─────────────────────── PLATFORM DATA (from spec) ─────────────────────── */
type TierItem = {
  name: string;
  icon: LucideIcon;
  time: string;
  color: string;
  bg: string;
};

type BenefitItem = {
  icon: LucideIcon;
  title: string;
  desc: string;
};

type PlatformData = {
  name: string;
  tagline: string;
  trialDays: number;
  qualificationAnswers: number;
  quizPassPercent: number;
  quizPoints: number;
  tiers: TierItem[];
  studentBenefits: BenefitItem[];
  teacherBenefits: BenefitItem[];
};

const QUALIFICATION_ANSWERS = 10;

const PLATFORM: PlatformData = {
  name: "Question Hub",
  tagline: "Where questions find answers",
  trialDays: 3,
  qualificationAnswers: QUALIFICATION_ANSWERS,
  quizPassPercent: 90,
  quizPoints: 5,
  tiers: [
    {
      name: "Text",
      icon: FileTextIcon,
      time: "30 min",
      color: "#1f766e",
      bg: "rgba(31,118,110,0.12)",
    },
    {
      name: "Photo",
      icon: ImageIcon,
      time: "1 hour",
      color: "#2176ae",
      bg: "rgba(33,118,174,0.12)",
    },
    {
      name: "Video",
      icon: VideoIcon,
      time: "3 hours",
      color: "#7c3aed",
      bg: "rgba(124,58,237,0.12)",
    },
  ],
  studentBenefits: [
    {
      icon: MessagesSquareIcon,
      title: "Ask anything academic",
      desc: "Post questions with full context. Attach photos, choose text or video answers — pick the format that suits your problem.",
    },
    {
      icon: BrainCircuitIcon,
      title: "AI-powered quiz portal",
      desc: "50-question timed MCQs generated by AI. Score 90%+ to earn points redeemable on your next subscription.",
    },
    {
      icon: Users2Icon,
      title: "Help peers, earn rewards",
      desc: "Answer other students' questions. Our AI validates quality — earn points for every accepted answer.",
    },
    {
      icon: TrophyIcon,
      title: "Climb the leaderboard",
      desc: "Compete with classmates. Top contributors get recognised. Weekly resets keep the race fresh.",
    },
    {
      icon: WalletIcon,
      title: "Points → discounts",
      desc: "Accumulate points from quizzes and peer answers. Redeem them as discounts when your subscription renews.",
    },
    {
      icon: ShieldCheckIcon,
      title: "Private or public answers",
      desc: "Keep a solution to yourself or share it with the class. You decide the visibility before asking.",
    },
  ],
  teacherBenefits: [
    {
      icon: ZapIcon,
      title: "Earn per answer",
      desc: "Get paid for every question you solve. Higher tiers, better ratings, bigger payouts.",
    },
    {
      icon: BarChart3Icon,
      title: "Tier-based earnings",
      desc: "Text, Photo, and Video answers carry different rates. Specialize in what you're fastest at.",
    },
    {
      icon: StarIcon,
      title: "Reputation system",
      desc: "Students rate your solutions 1–5. Your score builds a reputation that drives more question matches.",
    },
    {
      icon: AwardIcon,
      title: "Unlock monetization fast",
      desc: `Answer your first ${QUALIFICATION_ANSWERS} questions to complete qualification. Earnings unlock automatically — no waiting.`,
    },
    {
      icon: ClockIcon,
      title: "Strict SLA, fair rules",
      desc: "Tier-based time limits keep the platform fast. Miss a deadline? Channel auto-closes and the question resets — no gaming the queue.",
    },
    {
      icon: WalletIcon,
      title: "Withdraw any time",
      desc: "Earnings land in your platform wallet on every channel close. Request a withdrawal to your bank account whenever you want.",
    },
  ],
};

const HOW_IT_WORKS = [
  {
    step: "01",
    title: "Student asks",
    desc: "Write a question, choose answer format (Text / Photo / Video) and set visibility (public or private).",
  },
  {
    step: "02",
    title: "Teacher accepts",
    desc: "A teacher spots the question in the live feed, accepts it, and a private real-time channel opens instantly.",
  },
  {
    step: "03",
    title: "Answer delivered",
    desc: "The teacher submits the solution inside the channel before the timer runs out. Student rates and closes the thread.",
  },
];

/* ─────────────────────── SHARED HOOKS ─────────────────────── */
function useScrollReveal(threshold = 0.15) {
  const ref = useRef<HTMLDivElement>(null);
  const [visible, setVisible] = useState(false);
  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const obs = new IntersectionObserver(
      ([e]) => {
        if (e.isIntersecting) {
          setVisible(true);
          obs.disconnect();
        }
      },
      { threshold },
    );
    obs.observe(el);
    return () => obs.disconnect();
  }, [threshold]);
  return { ref, visible };
}

/* ─────────────────────── NAV ─────────────────────── */
function Nav() {
  const { resolvedTheme, setTheme } = useTheme();
  const [mounted, setMounted] = useState(false);
  const isDark = resolvedTheme === "dark";
  const [scrolled, setScrolled] = useState(false);

  useEffect(() => setMounted(true), []);

  useEffect(() => {
    const handler = () => setScrolled(window.scrollY > 20);
    window.addEventListener("scroll", handler, { passive: true });
    return () => window.removeEventListener("scroll", handler);
  }, []);

  return (
    <header
      style={{
        position: "sticky",
        top: 0,
        zIndex: 50,
        transition: "all 0.3s ease",
        borderBottom: scrolled
          ? "1px solid rgba(31,118,110,0.18)"
          : "1px solid transparent",
        background: scrolled
          ? isDark
            ? "rgba(15,25,20,0.82)"
            : "rgba(255,255,255,0.82)"
          : "transparent",
        backdropFilter: scrolled ? "blur(20px)" : "none",
      }}
    >
      <div
        style={{
          maxWidth: 1200,
          margin: "0 auto",
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          padding: "0 1.5rem",
          height: 64,
        }}
      >
        <Link
          href="/"
          style={{
            display: "flex",
            alignItems: "center",
            gap: 10,
            textDecoration: "none",
          }}
        >
          <div
            style={{
              width: 36,
              height: 36,
              borderRadius: 10,
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              overflow: "hidden",
            }}
          >
            <Image
              src="/logo.png"
              alt="Question Hub logo"
              width={26}
              height={26}
              priority
              style={{ width: "72%", height: "72%", objectFit: "contain" }}
            />
          </div>
          <span
            style={{
              fontSize: 17,
              fontWeight: 700,
              letterSpacing: "-0.03em",
              color: isDark ? "#e8f5f3" : "#0f3d38",
            }}
          >
            Question Hub
          </span>
        </Link>

        <nav style={{ display: "flex", alignItems: "center", gap: 8 }}>
          {[
            ["#how-it-works", "How it works"],
            ["#for-students", "Students"],
            ["#for-teachers", "Teachers"],
            ["#quiz", "Quiz"],
            ["/courses", "Courses"],
          ].map(([href, label]) => (
            <a
              key={href}
              href={href}
              style={{
                display: "none",
                padding: "0.4rem 0.8rem",
                fontSize: 14,
                fontWeight: 500,
                color: isDark ? "#9dc8c3" : "#2a6b64",
                textDecoration: "none",
                borderRadius: 8,
                transition: "all 0.15s",
              }}
              className="nav-link"
            >
              {label}
            </a>
          ))}

          <button
            onClick={() => setTheme(isDark ? "light" : "dark")}
            style={{
              width: 36,
              height: 36,
              borderRadius: 8,
              border: "1px solid rgba(31,118,110,0.25)",
              background: "transparent",
              cursor: "pointer",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              color: isDark ? "#9dc8c3" : "#2a6b64",
            }}
          >
            {mounted && (isDark ? <SunIcon size={16} /> : <MoonIcon size={16} />)}
          </button>

          <Link
            href={getSignInPath()}
            className="lpb-btn lpb-btn-ghost"
            style={{
              padding: "0.45rem 1rem",
              fontSize: 14,
              fontWeight: 600,
              borderRadius: 8,
              border: "1px solid rgba(31,118,110,0.3)",
              color: isDark ? "#9dc8c3" : "#1f766e",
              textDecoration: "none",
              background: "transparent",
            }}
          >
            Sign in
          </Link>
          <Link
            href={getSignUpPath("STUDENT")}
            className="lpb-btn lpb-btn-primary"
            style={{
              padding: "0.45rem 1.1rem",
              fontSize: 14,
              fontWeight: 600,
              borderRadius: 8,
              color: "#fff",
              textDecoration: "none",
            }}
          >
            Get started
          </Link>
        </nav>
      </div>
      <style>{`.nav-link{display:none!important}@media(min-width:768px){.nav-link{display:block!important}}`}</style>
    </header>
  );
}

/* ─────────────────────── HERO ─────────────────────── */
function Hero({ isDark }: { isDark: boolean }) {
  const [count, setCount] = useState(0);
  useEffect(() => {
    const t = setTimeout(() => setCount(1), 100);
    return () => clearTimeout(t);
  }, []);

  return (
    <section
      style={{
        position: "relative",
        overflow: "hidden",
        minHeight: "92vh",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        padding: "6rem 1.5rem 4rem",
      }}
    >
      {/* Ambient blobs */}
      <div
        style={{
          position: "absolute",
          inset: 0,
          pointerEvents: "none",
          overflow: "hidden",
        }}
      >
        <div
          style={{
            position: "absolute",
            top: "-15%",
            right: "5%",
            width: 600,
            height: 600,
            borderRadius: "50%",
            background:
              "radial-gradient(circle,rgba(31,118,110,0.18) 0%,transparent 70%)",
            filter: "blur(60px)",
          }}
        />
        <div
          style={{
            position: "absolute",
            bottom: "0%",
            left: "-10%",
            width: 500,
            height: 500,
            borderRadius: "50%",
            background:
              "radial-gradient(circle,rgba(33,118,174,0.12) 0%,transparent 70%)",
            filter: "blur(60px)",
          }}
        />
        <div
          style={{
            position: "absolute",
            top: "40%",
            left: "40%",
            width: 400,
            height: 400,
            borderRadius: "50%",
            background:
              "radial-gradient(circle,rgba(124,58,237,0.07) 0%,transparent 70%)",
            filter: "blur(80px)",
          }}
        />
        {/* Grid pattern */}
        <div
          style={{
            position: "absolute",
            inset: 0,
            backgroundImage: `url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%231f766e' fill-opacity='${isDark ? "0.04" : "0.06"}'%3E%3Cpath d='M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E")`,
          }}
        />
      </div>

      <div style={{ position: "relative", maxWidth: 900, textAlign: "center" }}>
        {/* Pill badge */}
        <div
          style={{
            display: "inline-flex",
            alignItems: "center",
            gap: 8,
            padding: "0.4rem 1rem",
            borderRadius: 100,
            border: `1px solid rgba(31,118,110,${isDark ? "0.4" : "0.3"})`,
            background: isDark
              ? "rgba(31,118,110,0.12)"
              : "rgba(31,118,110,0.07)",
            marginBottom: "1.5rem",
            transition: "all 0.4s",
            opacity: count ? 1 : 0,
            transform: count ? "translateY(0)" : "translateY(-10px)",
          }}
        >
          <GraduationCapIcon size={14} color="#1f766e" />
          <span
            style={{
              fontSize: 13,
              fontWeight: 600,
              color: "#1f766e",
              letterSpacing: "0.05em",
            }}
          >
            The Q&A platform for classrooms
          </span>
        </div>

        <h1
          style={{
            fontSize: "clamp(2.6rem,6vw,4.5rem)",
            fontWeight: 800,
            lineHeight: 1.08,
            letterSpacing: "-0.04em",
            color: isDark ? "#e8f5f3" : "#0a2e2a",
            marginBottom: "1.5rem",
            opacity: count ? 1 : 0,
            transform: count ? "translateY(0)" : "translateY(20px)",
            transition: "all 0.5s 0.1s",
          }}
        >
          Where questions find{" "}
          <span
            style={{
              background: "linear-gradient(135deg,#1f766e 30%,#2176ae)",
              WebkitBackgroundClip: "text",
              WebkitTextFillColor: "transparent",
              backgroundClip: "text",
            }}
          >
            real answers
          </span>
        </h1>

        <p
          style={{
            fontSize: "clamp(1rem,2vw,1.2rem)",
            lineHeight: 1.7,
            color: isDark ? "#7fb8b2" : "#3d6b64",
            maxWidth: 620,
            margin: "0 auto 2.5rem",
            opacity: count ? 1 : 0,
            transform: count ? "translateY(0)" : "translateY(20px)",
            transition: "all 0.5s 0.2s",
          }}
        >
          Students ask. Teachers answer. AI validates. Everyone wins.
          <br />A focused academic platform with quizzes, points, and real
          earnings — not just chat.
        </p>

        <div
          style={{
            display: "flex",
            flexWrap: "wrap",
            gap: 12,
            justifyContent: "center",
            marginBottom: "4rem",
            opacity: count ? 1 : 0,
            transform: count ? "translateY(0)" : "translateY(20px)",
            transition: "all 0.5s 0.3s",
          }}
        >
          <Link
            href={getSignUpPath("STUDENT")}
            className="lpb-btn lpb-btn-primary"
            style={{
              display: "inline-flex",
              alignItems: "center",
              gap: 8,
              padding: "0.8rem 1.8rem",
              borderRadius: 12,
              color: "#fff",
              fontWeight: 700,
              fontSize: 15,
              textDecoration: "none",
            }}
          >
            I&apos;m a Student <ArrowRightIcon size={16} />
          </Link>
          <Link
            href={getSignUpPath("TEACHER")}
            className={`lpb-btn ${isDark ? "lpb-btn-dark" : "lpb-btn-secondary"}`}
            style={{
              display: "inline-flex",
              alignItems: "center",
              gap: 8,
              padding: "0.8rem 1.8rem",
              borderRadius: 12,
              color: isDark ? "#9dc8c3" : "#1f766e",
              fontWeight: 700,
              fontSize: 15,
              textDecoration: "none",
              backdropFilter: "blur(10px)",
            }}
          >
            I&apos;m a Teacher
          </Link>
          <Link
            href={getSignInPath()}
            className="lpb-btn lpb-btn-ghost"
            style={{
              display: "inline-flex",
              alignItems: "center",
              gap: 6,
              padding: "0.8rem 1.4rem",
              borderRadius: 12,
              fontWeight: 600,
              fontSize: 14,
              textDecoration: "none",
            }}
          >
            Sign in →
          </Link>
        </div>

        {/* App preview mockup */}
        <HeroMockup isDark={isDark} />
      </div>

      <a
        href="#how-it-works"
        style={{
          position: "absolute",
          bottom: 32,
          left: "50%",
          transform: "translateX(-50%)",
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          gap: 6,
          color: isDark ? "#5a9990" : "#4a8a82",
          textDecoration: "none",
          animation: "bounce 2s infinite",
        }}
      >
        <span
          style={{
            fontSize: 12,
            fontWeight: 500,
            letterSpacing: "0.08em",
            opacity: 0.7,
          }}
        >
          SCROLL
        </span>
        <ChevronDownIcon size={20} />
      </a>

      <style>{`@keyframes bounce{0%,100%{transform:translateX(-50%) translateY(0)}50%{transform:translateX(-50%) translateY(-6px)}}`}</style>
    </section>
  );
}

/* ─────────────────────── HERO MOCKUP ─────────────────────── */
function HeroMockup({ isDark }: { isDark: boolean }) {
  const bg = isDark ? "rgba(15,35,30,0.85)" : "rgba(255,255,255,0.85)";
  const border = isDark ? "rgba(31,118,110,0.3)" : "rgba(31,118,110,0.2)";
  const card = isDark ? "rgba(31,118,110,0.12)" : "rgba(31,118,110,0.07)";
  const textMuted = isDark ? "#5a9990" : "#6aaba4";

  return (
    <div
      style={{
        position: "relative",
        maxWidth: 820,
        margin: "0 auto",
        borderRadius: 20,
        border: `1px solid ${border}`,
        background: bg,
        backdropFilter: "blur(24px)",
        boxShadow: `0 32px 80px rgba(0,0,0,${isDark ? "0.4" : "0.12"}), 0 0 0 1px ${border}`,
        overflow: "hidden",
      }}
    >
      {/* Window chrome */}
      <div
        style={{
          display: "flex",
          alignItems: "center",
          gap: 8,
          padding: "12px 16px",
          borderBottom: `1px solid ${border}`,
          background: isDark ? "rgba(10,30,25,0.6)" : "rgba(248,252,251,0.9)",
        }}
      >
        {["#ff5f56", "#ffbd2e", "#27c93f"].map((c) => (
          <div
            key={c}
            style={{
              width: 11,
              height: 11,
              borderRadius: "50%",
              background: c,
              opacity: 0.8,
            }}
          />
        ))}
        <div
          style={{
            flex: 1,
            height: 22,
            borderRadius: 6,
            background: isDark ? "rgba(255,255,255,0.06)" : "rgba(0,0,0,0.05)",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          <span style={{ fontSize: 11, color: textMuted }}>
            questionhub.app/feed
          </span>
        </div>
      </div>

      {/* Content area */}
      <div
        style={{
          display: "grid",
          gridTemplateColumns: "220px 1fr",
          minHeight: 320,
        }}
      >
        {/* Sidebar */}
        <div
          style={{
            borderRight: `1px solid ${border}`,
            padding: "16px 12px",
            display: "flex",
            flexDirection: "column",
            gap: 4,
          }}
        >
          {[
            { icon: "📚", label: "Feed", active: true },
            { icon: "💬", label: "My Channels" },
            { icon: "🏆", label: "Leaderboard" },
            { icon: "🧠", label: "Quiz" },
            { icon: "📖", label: "Courses" },
            { icon: "👛", label: "Wallet" },
          ].map(({ icon, label, active }) => (
            <div
              key={label}
              style={{
                display: "flex",
                alignItems: "center",
                gap: 8,
                padding: "7px 10px",
                borderRadius: 8,
                background: active ? "rgba(31,118,110,0.2)" : "transparent",
                cursor: "default",
              }}
            >
              <span style={{ fontSize: 13 }}>{icon}</span>
              <span
                style={{
                  fontSize: 13,
                  fontWeight: active ? 700 : 400,
                  color: active ? "#1f766e" : textMuted,
                }}
              >
                {label}
              </span>
            </div>
          ))}
        </div>

        {/* Feed */}
        <div
          style={{
            padding: 16,
            display: "flex",
            flexDirection: "column",
            gap: 10,
          }}
        >
          <p
            style={{
              fontSize: 11,
              fontWeight: 700,
              color: textMuted,
              letterSpacing: "0.08em",
              marginBottom: 4,
            }}
          >
            OPEN QUESTIONS
          </p>
          {[
            {
              q: "How do I solve this quadratic inequality?",
              tier: "Text",
              subject: "Math",
              time: "2m ago",
              replies: 0,
            },
            {
              q: "Explain Newton's third law with diagrams",
              tier: "Photo",
              subject: "Physics",
              time: "8m ago",
              replies: 1,
            },
            {
              q: "Can you walk me through this proof?",
              tier: "Video",
              subject: "Math",
              time: "14m ago",
              replies: 0,
            },
          ].map(({ q, tier, subject, time, replies }) => {
            const tColor =
              tier === "Text"
                ? "#1f766e"
                : tier === "Photo"
                  ? "#2176ae"
                  : "#7c3aed";
            return (
              <div
                key={q}
                style={{
                  padding: "10px 12px",
                  borderRadius: 10,
                  border: `1px solid ${border}`,
                  background: card,
                  cursor: "default",
                }}
              >
                <div
                  style={{
                    display: "flex",
                    alignItems: "center",
                    gap: 6,
                    marginBottom: 6,
                  }}
                >
                  <span
                    style={{
                      fontSize: 10,
                      fontWeight: 700,
                      color: tColor,
                      background: `${tColor}18`,
                      padding: "2px 7px",
                      borderRadius: 5,
                    }}
                  >
                    {tier}
                  </span>
                  <span
                    style={{
                      fontSize: 10,
                      color: textMuted,
                      background: isDark
                        ? "rgba(255,255,255,0.06)"
                        : "rgba(0,0,0,0.06)",
                      padding: "2px 7px",
                      borderRadius: 5,
                    }}
                  >
                    {subject}
                  </span>
                  <span
                    style={{
                      fontSize: 10,
                      color: textMuted,
                      marginLeft: "auto",
                    }}
                  >
                    {time}
                  </span>
                </div>
                <p
                  style={{
                    fontSize: 12.5,
                    fontWeight: 500,
                    color: isDark ? "#c8e6e2" : "#1a4a45",
                    margin: 0,
                    lineHeight: 1.4,
                  }}
                >
                  {q}
                </p>
                {replies > 0 && (
                  <p
                    style={{
                      fontSize: 11,
                      color: "#1f766e",
                      margin: "4px 0 0",
                      fontWeight: 600,
                    }}
                  >
                    ✓ {replies} answer
                  </p>
                )}
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}

/* ─────────────────────── STATS BAR ─────────────────────── */
function StatsBar({ isDark }: { isDark: boolean }) {
  const stats = [
    { value: "3-day", label: "Free trial" },
    { value: "3 tiers", label: "Answer formats" },
    { value: `${PLATFORM.quizPassPercent}%`, label: "Quiz pass → points" },
    {
      value: `${PLATFORM.qualificationAnswers} answers`,
      label: "Teacher qualification",
    },
    { value: "Real-time", label: "Private channels" },
  ];
  return (
    <div
      style={{
        borderTop: `1px solid rgba(31,118,110,${isDark ? "0.2" : "0.15"})`,
        borderBottom: `1px solid rgba(31,118,110,${isDark ? "0.2" : "0.15"})`,
        background: isDark ? "rgba(15,35,30,0.5)" : "rgba(31,118,110,0.04)",
        backdropFilter: "blur(10px)",
        overflowX: "auto",
      }}
    >
      <div
        style={{
          maxWidth: 1100,
          margin: "0 auto",
          display: "flex",
          justifyContent: "space-around",
          padding: "1.2rem 1.5rem",
          gap: 24,
          minWidth: 500,
        }}
      >
        {stats.map(({ value, label }) => (
          <div key={label} style={{ textAlign: "center", flexShrink: 0 }}>
            <p
              style={{
                fontSize: 18,
                fontWeight: 800,
                color: "#1f766e",
                margin: "0 0 2px",
                letterSpacing: "-0.03em",
              }}
            >
              {value}
            </p>
            <p
              style={{
                fontSize: 12,
                color: isDark ? "#5a9990" : "#5a8a84",
                margin: 0,
                whiteSpace: "nowrap",
              }}
            >
              {label}
            </p>
          </div>
        ))}
      </div>
    </div>
  );
}

/* ─────────────────────── HOW IT WORKS ─────────────────────── */
function HowItWorks({ isDark }: { isDark: boolean }) {
  const { ref, visible } = useScrollReveal();
  return (
    <section
      id="how-it-works"
      ref={ref}
      style={{ padding: "6rem 1.5rem", maxWidth: 1100, margin: "0 auto" }}
    >
      <SectionLabel label="How it works" />
      <h2 style={headingStyle(isDark)}>Three steps to an answer</h2>
      <p style={subStyle(isDark)}>
        A focused, time-bound workflow that keeps both sides accountable.
      </p>

      <div
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(auto-fit,minmax(260px,1fr))",
          gap: 24,
          marginTop: "3rem",
        }}
      >
        {HOW_IT_WORKS.map(({ step, title, desc }, i) => (
          <div
            key={step}
            style={{
              ...glassCard(isDark),
              opacity: visible ? 1 : 0,
              transform: visible ? "translateY(0)" : "translateY(30px)",
              transition: `all 0.5s ${i * 0.12}s`,
              position: "relative",
              overflow: "hidden",
            }}
          >
            <div
              style={{
                position: "absolute",
                top: -16,
                right: -8,
                fontSize: 80,
                fontWeight: 900,
                color: isDark
                  ? "rgba(31,118,110,0.08)"
                  : "rgba(31,118,110,0.07)",
                lineHeight: 1,
                pointerEvents: "none",
                userSelect: "none",
              }}
            >
              {step}
            </div>
            <div
              style={{
                width: 44,
                height: 44,
                borderRadius: 12,
                background:
                  "linear-gradient(135deg,rgba(31,118,110,0.25),rgba(31,118,110,0.1))",
                border: "1px solid rgba(31,118,110,0.3)",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                marginBottom: 16,
              }}
            >
              <span style={{ fontSize: 18, fontWeight: 800, color: "#1f766e" }}>
                {step}
              </span>
            </div>
            <h3
              style={{
                fontSize: 17,
                fontWeight: 700,
                color: isDark ? "#c8e6e2" : "#0a2e2a",
                margin: "0 0 8px",
                letterSpacing: "-0.02em",
              }}
            >
              {title}
            </h3>
            <p
              style={{
                fontSize: 14,
                lineHeight: 1.65,
                color: isDark ? "#6aaba4" : "#4a7a74",
                margin: 0,
              }}
            >
              {desc}
            </p>
          </div>
        ))}
      </div>

      {/* Tier cards */}
      <div style={{ marginTop: "3.5rem" }}>
        <p
          style={{
            textAlign: "center",
            fontSize: 13,
            fontWeight: 700,
            color: isDark ? "#5a9990" : "#5a8a84",
            letterSpacing: "0.1em",
            marginBottom: "1.5rem",
          }}
        >
          ANSWER FORMATS (TIERS)
        </p>
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fit,minmax(200px,1fr))",
            gap: 16,
          }}
        >
          {PLATFORM.tiers.map(({ name, icon: Icon, time, color, bg }, i) => (
            <div
              key={name}
              style={{
                ...glassCard(isDark),
                display: "flex",
                alignItems: "center",
                gap: 14,
                opacity: visible ? 1 : 0,
                transform: visible ? "translateY(0)" : "translateY(20px)",
                transition: `all 0.45s ${0.4 + i * 0.1}s`,
              }}
            >
              <div
                style={{
                  width: 42,
                  height: 42,
                  borderRadius: 10,
                  background: bg,
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  flexShrink: 0,
                }}
              >
                <Icon size={20} color={color} />
              </div>
              <div>
                <p
                  style={{
                    fontSize: 15,
                    fontWeight: 700,
                    color: isDark ? "#c8e6e2" : "#0a2e2a",
                    margin: "0 0 2px",
                  }}
                >
                  {name} Answer
                </p>
                <p
                  style={{
                    fontSize: 12,
                    color: isDark ? "#5a9990" : "#5a8a84",
                    margin: 0,
                  }}
                >
                  Time limit: {time}
                </p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

/* ─────────────────────── FOR STUDENTS ─────────────────────── */
function ForStudents({ isDark }: { isDark: boolean }) {
  const { ref, visible } = useScrollReveal();
  return (
    <section
      id="for-students"
      ref={ref}
      style={{
        padding: "6rem 1.5rem",
        background: isDark ? "rgba(10,30,25,0.6)" : "rgba(31,118,110,0.04)",
        borderTop: `1px solid rgba(31,118,110,${isDark ? "0.15" : "0.1"})`,
        borderBottom: `1px solid rgba(31,118,110,${isDark ? "0.15" : "0.1"})`,
      }}
    >
      <div style={{ maxWidth: 1100, margin: "0 auto" }}>
        <SectionLabel label="For Students" />
        <h2 style={headingStyle(isDark)}>Learn smarter, earn rewards</h2>
        <p style={subStyle(isDark)}>
          Start with a {PLATFORM.trialDays}-day free trial. Ask unlimited
          questions, quiz yourself, and rack up points.
        </p>

        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fit,minmax(300px,1fr))",
            gap: 20,
            marginTop: "3rem",
          }}
        >
          {PLATFORM.studentBenefits.map(({ icon: Icon, title, desc }, i) => (
            <FeatureCard
              key={title}
              Icon={Icon}
              title={title}
              desc={desc}
              isDark={isDark}
              delay={i * 0.08}
              visible={visible}
            />
          ))}
        </div>

        {/* Student visual */}
        <div
          style={{
            marginTop: "4rem",
            opacity: visible ? 1 : 0,
            transform: visible ? "translateY(0)" : "translateY(30px)",
            transition: "all 0.6s 0.4s",
          }}
        >
          <StudentQuizMockup isDark={isDark} />
        </div>
      </div>
    </section>
  );
}

function StudentQuizMockup({ isDark }: { isDark: boolean }) {
  const border = isDark ? "rgba(31,118,110,0.25)" : "rgba(31,118,110,0.18)";
  const cardBg = isDark ? "rgba(15,35,30,0.9)" : "rgba(255,255,255,0.92)";
  const textMuted = isDark ? "#5a9990" : "#6aaba4";

  return (
    <div
      style={{
        display: "grid",
        gridTemplateColumns: "repeat(auto-fit,minmax(280px,1fr))",
        gap: 20,
      }}
    >
      {/* Quiz card */}
      <div
        style={{
          borderRadius: 18,
          border: `1px solid ${border}`,
          background: cardBg,
          backdropFilter: "blur(20px)",
          overflow: "hidden",
          boxShadow: `0 20px 60px rgba(0,0,0,${isDark ? "0.35" : "0.08"})`,
        }}
      >
        <div
          style={{
            padding: "14px 16px",
            borderBottom: `1px solid ${border}`,
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
          }}
        >
          <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
            <BrainCircuitIcon size={15} color="#1f766e" />
            <span
              style={{
                fontSize: 13,
                fontWeight: 700,
                color: isDark ? "#c8e6e2" : "#0a2e2a",
              }}
            >
              Quiz — Mathematics · Grade 10
            </span>
          </div>
          <span
            style={{
              fontSize: 12,
              fontWeight: 700,
              color: "#e05c2a",
              background: "rgba(224,92,42,0.12)",
              padding: "2px 8px",
              borderRadius: 6,
            }}
          >
            12:43
          </span>
        </div>
        <div style={{ padding: 16 }}>
          <div style={{ marginBottom: 12 }}>
            <div
              style={{
                display: "flex",
                justifyContent: "space-between",
                marginBottom: 6,
              }}
            >
              <span style={{ fontSize: 11, color: textMuted }}>
                Question 23 of 50
              </span>
              <span style={{ fontSize: 11, color: "#1f766e", fontWeight: 700 }}>
                46% done
              </span>
            </div>
            <div
              style={{
                height: 5,
                borderRadius: 3,
                background: isDark
                  ? "rgba(255,255,255,0.08)"
                  : "rgba(0,0,0,0.07)",
                overflow: "hidden",
              }}
            >
              <div
                style={{
                  width: "46%",
                  height: "100%",
                  borderRadius: 3,
                  background: "linear-gradient(90deg,#1f766e,#2ab5ab)",
                }}
              />
            </div>
          </div>
          <p
            style={{
              fontSize: 13.5,
              fontWeight: 600,
              color: isDark ? "#c8e6e2" : "#0a2e2a",
              marginBottom: 14,
              lineHeight: 1.5,
            }}
          >
            What is the discriminant of the quadratic equation 2x² − 5x + 3 = 0?
          </p>
          {["A) 1", "B) 7", "C) 25", "D) −1"].map((opt, i) => (
            <div
              key={opt}
              style={{
                padding: "8px 12px",
                borderRadius: 8,
                border: `1px solid ${i === 0 ? "#1f766e" : border}`,
                background: i === 0 ? "rgba(31,118,110,0.12)" : "transparent",
                marginBottom: 8,
                fontSize: 13,
                color: i === 0 ? "#1f766e" : isDark ? "#9dc8c3" : "#3d6b64",
                fontWeight: i === 0 ? 700 : 400,
                cursor: "default",
              }}
            >
              {opt}
            </div>
          ))}
        </div>
      </div>

      {/* Points + Leaderboard */}
      <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
        <div
          style={{
            borderRadius: 18,
            border: `1px solid ${border}`,
            background: cardBg,
            backdropFilter: "blur(20px)",
            padding: 20,
            boxShadow: `0 20px 60px rgba(0,0,0,${isDark ? "0.35" : "0.08"})`,
          }}
        >
          <p
            style={{
              fontSize: 12,
              color: textMuted,
              fontWeight: 600,
              letterSpacing: "0.06em",
              margin: "0 0 12px",
            }}
          >
            MY WALLET
          </p>
          <div
            style={{
              display: "flex",
              alignItems: "baseline",
              gap: 8,
              marginBottom: 14,
            }}
          >
            <span
              style={{
                fontSize: 38,
                fontWeight: 800,
                color: "#1f766e",
                letterSpacing: "-0.04em",
              }}
            >
              240
            </span>
            <span style={{ fontSize: 14, color: textMuted, fontWeight: 500 }}>
              points
            </span>
          </div>
          {[
            { label: "Quiz wins", pts: "+5 pts", color: "#1f766e" },
            { label: "Peer answers", pts: "+3 pts", color: "#2176ae" },
            {
              label: "Subscription discount",
              pts: "−50 pts",
              color: "#e05c2a",
            },
          ].map(({ label, pts, color }) => (
            <div
              key={label}
              style={{
                display: "flex",
                justifyContent: "space-between",
                padding: "6px 0",
                borderTop: `1px solid ${border}`,
              }}
            >
              <span
                style={{
                  fontSize: 12.5,
                  color: isDark ? "#9dc8c3" : "#3d6b64",
                }}
              >
                {label}
              </span>
              <span style={{ fontSize: 12.5, fontWeight: 700, color }}>
                {pts}
              </span>
            </div>
          ))}
        </div>

        <div
          style={{
            borderRadius: 18,
            border: `1px solid ${border}`,
            background: cardBg,
            backdropFilter: "blur(20px)",
            padding: 20,
            boxShadow: `0 20px 60px rgba(0,0,0,${isDark ? "0.35" : "0.08"})`,
          }}
        >
          <p
            style={{
              fontSize: 12,
              color: textMuted,
              fontWeight: 600,
              letterSpacing: "0.06em",
              margin: "0 0 12px",
            }}
          >
            LEADERBOARD
          </p>
          {[
            { rank: 1, name: "Priya S.", pts: 840, badge: "🥇" },
            { rank: 2, name: "Rohan M.", pts: 720, badge: "🥈" },
            { rank: 3, name: "You", pts: 240, badge: "🎯", highlight: true },
          ].map(({ rank, name, pts, badge, highlight }) => (
            <div
              key={rank}
              style={{
                display: "flex",
                alignItems: "center",
                gap: 10,
                padding: "7px 10px",
                borderRadius: 8,
                background: highlight ? "rgba(31,118,110,0.12)" : "transparent",
                marginBottom: 4,
              }}
            >
              <span style={{ fontSize: 15 }}>{badge}</span>
              <span
                style={{
                  fontSize: 13,
                  flex: 1,
                  fontWeight: highlight ? 700 : 400,
                  color: isDark ? "#c8e6e2" : "#0a2e2a",
                }}
              >
                {name}
              </span>
              <span style={{ fontSize: 12, fontWeight: 700, color: "#1f766e" }}>
                {pts} pts
              </span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

/* ─────────────────────── FOR TEACHERS ─────────────────────── */
function ForTeachers({ isDark }: { isDark: boolean }) {
  const { ref, visible } = useScrollReveal();
  return (
    <section
      id="for-teachers"
      ref={ref}
      style={{ padding: "6rem 1.5rem", maxWidth: 1100, margin: "0 auto" }}
    >
      <SectionLabel label="For Teachers" />
      <h2 style={headingStyle(isDark)}>Answer questions. Earn real money.</h2>
      <p style={subStyle(isDark)}>
        Build your reputation, qualify in your first{" "}
        {PLATFORM.qualificationAnswers} answers, then get paid per solution.
      </p>

      <div
        style={{
          display: "grid",
          gridTemplateColumns: "1fr 1fr",
          gap: 24,
          marginTop: "3.5rem",
        }}
      >
        <div style={{ display: "grid", gridTemplateColumns: "1fr", gap: 16 }}>
          {PLATFORM.teacherBenefits.map(({ icon: Icon, title, desc }, i) => (
            <FeatureCard
              key={title}
              Icon={Icon}
              title={title}
              desc={desc}
              isDark={isDark}
              delay={i * 0.07}
              visible={visible}
              compact
            />
          ))}
        </div>

        <div
          style={{
            opacity: visible ? 1 : 0,
            transform: visible ? "translateX(0)" : "translateX(30px)",
            transition: "all 0.6s 0.3s",
          }}
        >
          <TeacherMockup isDark={isDark} />
        </div>
      </div>
    </section>
  );
}

function TeacherMockup({ isDark }: { isDark: boolean }) {
  const border = isDark ? "rgba(31,118,110,0.25)" : "rgba(31,118,110,0.18)";
  const cardBg = isDark ? "rgba(15,35,30,0.9)" : "rgba(255,255,255,0.92)";
  const textMuted = isDark ? "#5a9990" : "#6aaba4";

  return (
    <div
      style={{
        borderRadius: 20,
        border: `1px solid ${border}`,
        background: cardBg,
        backdropFilter: "blur(20px)",
        overflow: "hidden",
        boxShadow: `0 24px 60px rgba(0,0,0,${isDark ? "0.35" : "0.1"})`,
        height: "100%",
      }}
    >
      <div
        style={{
          padding: "14px 16px",
          borderBottom: `1px solid ${border}`,
          display: "flex",
          alignItems: "center",
          gap: 10,
        }}
      >
        <div
          style={{
            width: 32,
            height: 32,
            borderRadius: "50%",
            background: "linear-gradient(135deg,#1f766e,#0f5c55)",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          <span style={{ fontSize: 14, fontWeight: 700, color: "#fff" }}>
            SK
          </span>
        </div>
        <div>
          <p
            style={{
              fontSize: 13,
              fontWeight: 700,
              color: isDark ? "#c8e6e2" : "#0a2e2a",
              margin: 0,
            }}
          >
            Santosh K. — Teacher
          </p>
          <p
            style={{
              fontSize: 11,
              color: "#1f766e",
              margin: 0,
              fontWeight: 600,
            }}
          >
            ✓ Monetized · 42 answers
          </p>
        </div>
      </div>

      {/* Wallet */}
      <div
        style={{
          padding: "14px 16px",
          borderBottom: `1px solid ${border}`,
          background: isDark
            ? "rgba(31,118,110,0.08)"
            : "rgba(31,118,110,0.05)",
        }}
      >
        <p
          style={{
            fontSize: 11,
            color: textMuted,
            fontWeight: 700,
            letterSpacing: "0.08em",
            margin: "0 0 6px",
          }}
        >
          WALLET BALANCE
        </p>
        <p
          style={{
            fontSize: 28,
            fontWeight: 800,
            color: "#1f766e",
            margin: "0 0 10px",
            letterSpacing: "-0.04em",
          }}
        >
          रू 1,840
        </p>
        <div style={{ display: "flex", gap: 8 }}>
          <div
            style={{
              flex: 1,
              padding: "6px 10px",
              borderRadius: 8,
              background: isDark
                ? "rgba(255,255,255,0.06)"
                : "rgba(0,0,0,0.04)",
              fontSize: 11,
              color: textMuted,
            }}
          >
            <p style={{ margin: 0, fontWeight: 700 }}>रू 240</p>
            <p style={{ margin: 0 }}>This week</p>
          </div>
          <div
            style={{
              flex: 1,
              padding: "6px 10px",
              borderRadius: 8,
              background: isDark
                ? "rgba(255,255,255,0.06)"
                : "rgba(0,0,0,0.04)",
              fontSize: 11,
              color: textMuted,
            }}
          >
            <p style={{ margin: 0, fontWeight: 700 }}>4.7 ★</p>
            <p style={{ margin: 0 }}>Avg rating</p>
          </div>
        </div>
      </div>

      {/* Recent earnings */}
      <div style={{ padding: "14px 16px" }}>
        <p
          style={{
            fontSize: 11,
            color: textMuted,
            fontWeight: 700,
            letterSpacing: "0.08em",
            margin: "0 0 10px",
          }}
        >
          RECENT EARNINGS
        </p>
        {[
          {
            q: "Quadratic inequalities",
            tier: "Text",
            amount: "रू 85",
            rating: 5,
            time: "2h ago",
          },
          {
            q: "Newton's laws diagram",
            tier: "Photo",
            amount: "रू 140",
            rating: 4,
            time: "Yesterday",
          },
          {
            q: "Integration by parts",
            tier: "Video",
            amount: "रू 210",
            rating: 5,
            time: "2 days ago",
          },
        ].map(({ q, tier, amount, rating, time }) => {
          const tColor =
            tier === "Text"
              ? "#1f766e"
              : tier === "Photo"
                ? "#2176ae"
                : "#7c3aed";
          return (
            <div
              key={q}
              style={{
                display: "flex",
                alignItems: "center",
                gap: 10,
                padding: "8px 0",
                borderTop: `1px solid ${border}`,
              }}
            >
              <div style={{ flex: 1 }}>
                <p
                  style={{
                    fontSize: 12.5,
                    fontWeight: 600,
                    color: isDark ? "#c8e6e2" : "#0a2e2a",
                    margin: "0 0 2px",
                    lineHeight: 1.3,
                  }}
                >
                  {q}
                </p>
                <div style={{ display: "flex", alignItems: "center", gap: 6 }}>
                  <span
                    style={{
                      fontSize: 10,
                      fontWeight: 700,
                      color: tColor,
                      background: `${tColor}18`,
                      padding: "1px 6px",
                      borderRadius: 4,
                    }}
                  >
                    {tier}
                  </span>
                  <span style={{ fontSize: 10, color: textMuted }}>{time}</span>
                </div>
              </div>
              <div style={{ textAlign: "right", flexShrink: 0 }}>
                <p
                  style={{
                    fontSize: 13,
                    fontWeight: 800,
                    color: "#1f766e",
                    margin: "0 0 1px",
                  }}
                >
                  {amount}
                </p>
                <p style={{ fontSize: 11, color: "#f59e0b", margin: 0 }}>
                  {"★".repeat(rating)}
                </p>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}

/* ─────────────────────── QUIZ PORTAL ─────────────────────── */
function QuizPortal({ isDark }: { isDark: boolean }) {
  const { ref, visible } = useScrollReveal();
  return (
    <section
      id="quiz"
      ref={ref}
      style={{
        padding: "6rem 1.5rem",
        background: isDark ? "rgba(10,20,35,0.6)" : "rgba(33,118,174,0.04)",
        borderTop: `1px solid rgba(33,118,174,${isDark ? "0.2" : "0.12"})`,
        borderBottom: `1px solid rgba(33,118,174,${isDark ? "0.2" : "0.12"})`,
      }}
    >
      <div style={{ maxWidth: 1100, margin: "0 auto" }}>
        <SectionLabel label="Quiz Portal" color="#2176ae" />
        <h2 style={headingStyle(isDark)}>Test yourself. Earn points.</h2>
        <p style={subStyle(isDark)}>
          AI-generated 50-question MCQ sessions. Score{" "}
          {PLATFORM.quizPassPercent}%+ and earn {PLATFORM.quizPoints} points
          toward your next subscription. Available exclusively to active
          subscribers.
        </p>

        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fit,minmax(220px,1fr))",
            gap: 20,
            marginTop: "3rem",
          }}
        >
          {[
            {
              icon: BrainCircuitIcon,
              title: "AI-generated questions",
              desc: "Every quiz is freshly generated by AI for your chosen subject, topic, and grade level — no repeat questions for 15 days.",
              color: "#2176ae",
            },
            {
              icon: ClockIcon,
              title: "Timed challenge",
              desc: "Beat the clock. Admin-set time limits keep you focused. Unanswered questions count as wrong — no cheating the timer.",
              color: "#7c3aed",
            },
            {
              icon: SparklesIcon,
              title: "Instant feedback",
              desc: "See your score, correct answers, and AI explanations immediately after submitting. Learn from every mistake.",
              color: "#1f766e",
            },
            {
              icon: TrophyIcon,
              title: "Points that matter",
              desc: `Pass with ${PLATFORM.quizPassPercent}%+ and earn ${PLATFORM.quizPoints} points deposited to your wallet. Stack them for a free renewal.`,
              color: "#f59e0b",
            },
          ].map(({ icon: Icon, title, desc, color }, i) => (
            <div
              key={title}
              style={{
                ...glassCard(isDark),
                borderTop: `3px solid ${color}20`,
                opacity: visible ? 1 : 0,
                transform: visible ? "translateY(0)" : "translateY(24px)",
                transition: `all 0.5s ${i * 0.1}s`,
              }}
            >
              <div
                style={{
                  width: 40,
                  height: 40,
                  borderRadius: 10,
                  background: `${color}14`,
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  marginBottom: 14,
                }}
              >
                <Icon size={20} color={color} />
              </div>
              <h3
                style={{
                  fontSize: 15,
                  fontWeight: 700,
                  color: isDark ? "#c8e6e2" : "#0a2e2a",
                  margin: "0 0 8px",
                }}
              >
                {title}
              </h3>
              <p
                style={{
                  fontSize: 13.5,
                  color: isDark ? "#6aaba4" : "#4a7a74",
                  lineHeight: 1.6,
                  margin: 0,
                }}
              >
                {desc}
              </p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

/* ─────────────────────── COURSE LIBRARY ─────────────────────── */
function CourseLibrary({ isDark }: { isDark: boolean }) {
  const { ref, visible } = useScrollReveal();
  const border = isDark ? "rgba(31,118,110,0.22)" : "rgba(31,118,110,0.16)";

  const courses = [
    {
      subject: "Mathematics",
      title: "Complete Calculus Mastery",
      level: "Grade 11-12",
      uploader: "Aarav · Teacher",
      color: "#1f766e",
      pricing: "PAID",
      price: "रू 499",
      videos: 24,
      duration: "6h 30m",
      liveSessions: true,
      isFeatured: true,
    },
    {
      subject: "Physics",
      title: "Mechanics & Motion Fundamentals",
      level: "Grade 10",
      uploader: "Priya · Teacher",
      color: "#2176ae",
      pricing: "FREE",
      videos: 12,
      duration: "3h 15m",
      liveSessions: false,
      isFeatured: false,
    },
    {
      subject: "Chemistry",
      title: "Organic Chemistry Vol. I",
      level: "Grade 11",
      uploader: "Admin",
      color: "#7c3aed",
      pricing: "SUBSCRIPTION",
      videos: 18,
      duration: "5h 00m",
      liveSessions: true,
      isFeatured: false,
    },
    {
      subject: "Mathematics",
      title: "Algebra Essentials",
      level: "Grade 9",
      uploader: "Rohan · Teacher",
      color: "#f59e0b",
      pricing: "FREE",
      videos: 8,
      duration: "2h 10m",
      liveSessions: false,
      isFeatured: false,
    },
  ];

  const pricingBadge = (pricing: string, price?: string) => {
    if (pricing === "FREE") {
      return { bg: "rgba(34,197,94,0.15)", color: "#22c55e", label: "FREE" };
    } else if (pricing === "SUBSCRIPTION") {
      return { bg: "rgba(124,58,237,0.15)", color: "#7c3aed", label: "SUBSCRIPTION" };
    } else {
      return { bg: "rgba(245,158,11,0.15)", color: "#f59e0b", label: price || "PAID" };
    }
  };

  return (
    <section
      ref={ref}
      style={{ padding: "6rem 1.5rem", maxWidth: 1100, margin: "0 auto" }}
    >
      <SectionLabel label="Video Courses" />
      <h2 style={headingStyle(isDark)}>Learn at your own pace with expert-led video courses</h2>
      <p style={subStyle(isDark)}>
        Structured video courses created by verified teachers. Three pricing options — free, subscription-inclusive, or one-time purchase. Includes progress tracking and live sessions for premium courses.
      </p>

      <div
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(auto-fill,minmax(260px,1fr))",
          gap: 20,
          marginTop: "3rem",
        }}
      >
        {courses.map(({ subject, title, level, uploader, color, pricing, price, videos, duration, liveSessions, isFeatured }, i) => {
          const badge = pricingBadge(pricing, price);
          return (
            <div
              key={title}
              style={{
                borderRadius: 18,
                border: `1px solid ${border}`,
                background: isDark
                  ? "rgba(15,35,30,0.7)"
                  : "rgba(255,255,255,0.85)",
                backdropFilter: "blur(16px)",
                overflow: "hidden",
                cursor: "default",
                opacity: visible ? 1 : 0,
                transform: visible ? "translateY(0)" : "translateY(20px)",
                transition: `all 0.45s ${i * 0.08}s`,
                boxShadow: `0 4px 20px rgba(0,0,0,${isDark ? "0.25" : "0.05"})`,
                position: "relative",
              }}
            >
              {isFeatured && (
                <div
                  style={{
                    position: "absolute",
                    top: 12,
                    left: 12,
                    zIndex: 10,
                    background: "linear-gradient(135deg,#f59e0b,#e05c2a)",
                    color: "#fff",
                    fontSize: 10,
                    fontWeight: 700,
                    padding: "3px 10px",
                    borderRadius: 20,
                    letterSpacing: "0.05em",
                  }}
                >
                  FEATURED
                </div>
              )}

              <div
                style={{
                  height: 140,
                  background: `linear-gradient(135deg,${color}25,${color}08)`,
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  borderBottom: `1px solid ${border}`,
                  position: "relative",
                }}
              >
                <div
                  style={{
                    position: "absolute",
                    inset: 0,
                    backgroundImage: `repeating-linear-gradient(45deg,${color}08 0,${color}08 1px,transparent 0,transparent 50%)`,
                    backgroundSize: "20px 20px",
                  }}
                />
                <div
                  style={{
                    width: 64,
                    height: 64,
                    borderRadius: "50%",
                    background: `${color}20`,
                    border: `2px solid ${color}40`,
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    position: "relative",
                  }}
                >
                  <PlayCircleIcon size={28} color={color} />
                </div>
              </div>

              <div style={{ padding: "14px 16px" }}>
                <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 8 }}>
                  <span
                    style={{
                      fontSize: 10,
                      fontWeight: 700,
                      color: color,
                      background: `${color}15`,
                      padding: "2px 7px",
                      borderRadius: 5,
                      letterSpacing: "0.04em",
                    }}
                  >
                    {subject} · {level}
                  </span>
                </div>

                <p
                  style={{
                    fontSize: 15,
                    fontWeight: 700,
                    color: isDark ? "#c8e6e2" : "#0a2e2a",
                    margin: "0 0 8px",
                    lineHeight: 1.3,
                  }}
                >
                  {title}
                </p>

                <div style={{ display: "flex", alignItems: "center", gap: 6, marginBottom: 10 }}>
                  <PlayCircleIcon size={12} color={isDark ? "#5a9990" : "#6aaba4"} />
                  <span style={{ fontSize: 11, color: isDark ? "#5a9990" : "#6aaba4" }}>
                    {videos} videos · {duration}
                  </span>
                  {liveSessions && (
                    <>
                      <span style={{ color: isDark ? "#5a9990" : "#6aaba4" }}>·</span>
                      <CalendarIcon size={12} color="#7c3aed" />
                      <span style={{ fontSize: 11, color: "#7c3aed", fontWeight: 600 }}>
                        Live
                      </span>
                    </>
                  )}
                </div>

                <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
                  <span
                    style={{
                      fontSize: 11,
                      fontWeight: 700,
                      color: badge.color,
                      background: badge.bg,
                      padding: "4px 10px",
                      borderRadius: 6,
                    }}
                  >
                    {badge.label}
                  </span>
                  <span style={{ fontSize: 10, color: isDark ? "#5a9990" : "#6aaba4" }}>
                    by {uploader}
                  </span>
                </div>
              </div>
            </div>
          );
        })}
      </div>

      <div
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(auto-fit,minmax(220px,1fr))",
          gap: 16,
          marginTop: "3rem",
        }}
      >
        {[
          {
            icon: BookOpenIcon,
            title: "Video-based learning",
            desc: "High-quality recorded lessons organized by sections. Watch anytime, anywhere.",
            color: "#1f766e",
          },
          {
            icon: PlayCircleIcon,
            title: "Progress tracking",
            desc: "Track your watch time. Complete videos to mark progress. Pick up where you left off.",
            color: "#2176ae",
          },
          {
            icon: CalendarIcon,
            title: "Live sessions (premium)",
            desc: "Subscribe or purchase to join live classes with teachers via Zoom. Get real-time help.",
            color: "#7c3aed",
          },
          {
            icon: UsersIcon,
            title: "Instructor-led courses",
            desc: "Courses created by verified teachers and admins. Quality content, structured learning.",
            color: "#f59e0b",
          },
        ].map(({ icon: Icon, title, desc, color }, i) => (
          <div
            key={title}
            style={{
              ...glassCard(isDark),
              display: "flex",
              alignItems: "flex-start",
              gap: 12,
              opacity: visible ? 1 : 0,
              transform: visible ? "translateY(0)" : "translateY(16px)",
              transition: `all 0.4s ${0.5 + i * 0.08}s`,
            }}
          >
            <div
              style={{
                width: 36,
                height: 36,
                borderRadius: 10,
                background: `${color}15`,
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                flexShrink: 0,
              }}
            >
              <Icon size={18} color={color} />
            </div>
            <div>
              <p
                style={{
                  fontSize: 14,
                  fontWeight: 700,
                  color: isDark ? "#c8e6e2" : "#0a2e2a",
                  margin: "0 0 4px",
                }}
              >
                {title}
              </p>
              <p
                style={{
                  fontSize: 12.5,
                  color: isDark ? "#6aaba4" : "#4a7a74",
                  margin: 0,
                  lineHeight: 1.5,
                }}
              >
                {desc}
              </p>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}

/* ─────────────────────── TRUST / COMPARISON ─────────────────────── */
function Comparison({ isDark }: { isDark: boolean }) {
  const { ref, visible } = useScrollReveal();
  const rows = [
    { feature: "Time-bounded answers", us: true, other: false },
    { feature: "Tiered answer formats", us: true, other: false },
    { feature: "Teacher monetization", us: true, other: false },
    { feature: "AI quiz generation", us: true, other: false },
    { feature: "Points & rewards system", us: true, other: false },
    { feature: "Khalti & eSewa payments", us: true, other: false },
    { feature: "Public + private answers", us: true, other: true },
    { feature: "Real-time chat channels", us: true, other: true },
  ];
  const border = isDark ? "rgba(31,118,110,0.2)" : "rgba(31,118,110,0.15)";

  return (
    <section
      ref={ref}
      style={{
        padding: "6rem 1.5rem",
        background: isDark ? "rgba(10,30,25,0.5)" : "rgba(31,118,110,0.03)",
        borderTop: `1px solid ${border}`,
        borderBottom: `1px solid ${border}`,
      }}
    >
      <div style={{ maxWidth: 700, margin: "0 auto" }}>
        <SectionLabel label="Why Question Hub" />
        <h2 style={{ ...headingStyle(isDark), textAlign: "center" }}>
          Built different from the start
        </h2>

        <div
          style={{
            marginTop: "2.5rem",
            borderRadius: 18,
            border: `1px solid ${border}`,
            background: isDark
              ? "rgba(15,35,30,0.85)"
              : "rgba(255,255,255,0.9)",
            backdropFilter: "blur(20px)",
            overflow: "hidden",
            opacity: visible ? 1 : 0,
            transform: visible ? "translateY(0)" : "translateY(24px)",
            transition: "all 0.5s 0.1s",
            boxShadow: `0 20px 60px rgba(0,0,0,${isDark ? "0.3" : "0.07"})`,
          }}
        >
          <div
            style={{
              display: "grid",
              gridTemplateColumns: "1fr 120px 120px",
              borderBottom: `1px solid ${border}`,
              background: isDark
                ? "rgba(31,118,110,0.08)"
                : "rgba(31,118,110,0.06)",
            }}
          >
            <div style={{ padding: "12px 16px" }} />
            <div
              style={{
                padding: "12px 8px",
                textAlign: "center",
                fontSize: 12,
                fontWeight: 700,
                color: "#1f766e",
              }}
            >
              Question Hub
            </div>
            <div
              style={{
                padding: "12px 8px",
                textAlign: "center",
                fontSize: 12,
                fontWeight: 600,
                color: isDark ? "#5a9990" : "#8aaca8",
              }}
            >
              Generic Q&A
            </div>
          </div>
          {rows.map(({ feature, us, other }, i) => (
            <div
              key={feature}
              style={{
                display: "grid",
                gridTemplateColumns: "1fr 120px 120px",
                borderTop: i ? `1px solid ${border}` : "none",
              }}
            >
              <div
                style={{
                  padding: "11px 16px",
                  fontSize: 13.5,
                  color: isDark ? "#9dc8c3" : "#2a6b64",
                }}
              >
                {feature}
              </div>
              <div
                style={{
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                }}
              >
                {us ? (
                  <CheckCircleIcon size={17} color="#1f766e" />
                ) : (
                  <span
                    style={{ fontSize: 14, color: isDark ? "#5a9990" : "#aaa" }}
                  >
                    —
                  </span>
                )}
              </div>
              <div
                style={{
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                }}
              >
                {other ? (
                  <CheckCircleIcon size={17} color="#aaa" />
                ) : (
                  <span
                    style={{ fontSize: 14, color: isDark ? "#5a9990" : "#ccc" }}
                  >
                    —
                  </span>
                )}
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

/* ─────────────────────── CTA ─────────────────────── */
function CTASection({ isDark }: { isDark: boolean }) {
  const { ref, visible } = useScrollReveal();
  return (
    <section
      ref={ref}
      style={{
        padding: "7rem 1.5rem",
        textAlign: "center",
        position: "relative",
        overflow: "hidden",
      }}
    >
      <div style={{ position: "absolute", inset: 0, pointerEvents: "none" }}>
        <div
          style={{
            position: "absolute",
            top: "10%",
            left: "20%",
            width: 500,
            height: 500,
            borderRadius: "50%",
            background:
              "radial-gradient(circle,rgba(31,118,110,0.14) 0%,transparent 70%)",
            filter: "blur(80px)",
          }}
        />
        <div
          style={{
            position: "absolute",
            bottom: "0%",
            right: "15%",
            width: 400,
            height: 400,
            borderRadius: "50%",
            background:
              "radial-gradient(circle,rgba(33,118,174,0.1) 0%,transparent 70%)",
            filter: "blur(60px)",
          }}
        />
      </div>

      <div
        style={{
          position: "relative",
          maxWidth: 620,
          margin: "0 auto",
          opacity: visible ? 1 : 0,
          transform: visible ? "translateY(0)" : "translateY(30px)",
          transition: "all 0.6s",
        }}
      >
        <div
          style={{
            display: "inline-flex",
            alignItems: "center",
            gap: 8,
            padding: "0.4rem 1rem",
            borderRadius: 100,
            border: "1px solid rgba(31,118,110,0.35)",
            background: "rgba(31,118,110,0.08)",
            marginBottom: "1.5rem",
          }}
        >
          <SparklesIcon size={13} color="#1f766e" />
          <span
            style={{
              fontSize: 12.5,
              fontWeight: 700,
              color: "#1f766e",
              letterSpacing: "0.06em",
            }}
          >
            {PLATFORM.trialDays}-day free trial for students
          </span>
        </div>

        <h2
          style={{
            fontSize: "clamp(2rem,5vw,3.2rem)",
            fontWeight: 800,
            letterSpacing: "-0.04em",
            color: isDark ? "#e8f5f3" : "#0a2e2a",
            margin: "0 0 1rem",
            lineHeight: 1.1,
          }}
        >
          Ready to start?
        </h2>
        <p
          style={{
            fontSize: 17,
            color: isDark ? "#7fb8b2" : "#3d6b64",
            margin: "0 0 2.5rem",
            lineHeight: 1.6,
          }}
        >
          Join thousands of students and teachers on Question Hub — where every
          question gets a real answer.
        </p>

        <div
          style={{
            display: "flex",
            flexWrap: "wrap",
            gap: 14,
            justifyContent: "center",
          }}
        >
          <Link
            href={getSignUpPath("STUDENT")}
            className="lpb-btn lpb-btn-primary"
            style={{
              display: "inline-flex",
              alignItems: "center",
              gap: 8,
              padding: "0.9rem 2rem",
              borderRadius: 14,
              color: "#fff",
              fontWeight: 700,
              fontSize: 15.5,
              textDecoration: "none",
            }}
          >
            <GraduationCapIcon size={18} /> Sign up as Student
          </Link>
          <Link
            href={getSignUpPath("TEACHER")}
            className={`lpb-btn ${isDark ? "lpb-btn-dark" : "lpb-btn-secondary"}`}
            style={{
              display: "inline-flex",
              alignItems: "center",
              gap: 8,
              padding: "0.9rem 2rem",
              borderRadius: 14,
              color: isDark ? "#9dc8c3" : "#1f766e",
              fontWeight: 700,
              fontSize: 15.5,
              textDecoration: "none",
              backdropFilter: "blur(12px)",
            }}
          >
            <Users2Icon size={18} /> Sign up as Teacher
          </Link>
        </div>

        <p
          style={{
            fontSize: 13,
            color: isDark ? "#4a8a82" : "#7ab5ae",
            marginTop: "1.5rem",
          }}
        >
          No credit card required to start · Cancel any time
        </p>
      </div>
    </section>
  );
}

/* ─────────────────────── FOOTER ─────────────────────── */
function Footer({ isDark }: { isDark: boolean }) {
  const border = isDark ? "rgba(31,118,110,0.18)" : "rgba(31,118,110,0.14)";
  return (
    <footer
      style={{
        borderTop: `1px solid ${border}`,
        background: isDark ? "rgba(8,20,18,0.8)" : "rgba(248,252,251,0.9)",
        backdropFilter: "blur(10px)",
      }}
    >
      <div
        style={{
          maxWidth: 1100,
          margin: "0 auto",
          padding: "1.5rem 1.5rem",
          display: "flex",
          flexWrap: "wrap",
          alignItems: "center",
          justifyContent: "space-between",
          gap: 16,
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
          <div
            style={{
              width: 28,
              height: 28,
              borderRadius: 8,
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              overflow: "hidden",
            }}
          >
            <Image
              src="/logo.png"
              alt="Question Hub logo"
              width={20}
              height={20}
              style={{ width: "72%", height: "72%", objectFit: "contain" }}
            />
          </div>
          <span
            style={{
              fontSize: 14,
              fontWeight: 700,
              color: isDark ? "#9dc8c3" : "#1f766e",
            }}
          >
            Question Hub
          </span>
        </div>

        <div style={{ display: "flex", gap: 20 }}>
          {[
            [getSignInPath(), "Sign in"],
            [getSignUpPath("STUDENT"), "Students"],
            [getSignUpPath("TEACHER"), "Teachers"],
          ].map(([href, label]) => (
            <Link
              key={label}
              href={href}
              style={{
                fontSize: 13,
                color: isDark ? "#5a9990" : "#6aaba4",
                textDecoration: "none",
                fontWeight: 500,
              }}
            >
              {label}
            </Link>
          ))}
        </div>

        <div
          style={{
            display: "flex",
            flexDirection: "column",
            alignItems: "flex-end",
            gap: 4,
          }}
        >
          <p
            style={{
              fontSize: 12,
              color: isDark ? "#3a6a64" : "#9dc8c3",
              margin: 0,
            }}
          >
            © {new Date().getFullYear()} Question Hub. All rights reserved.
          </p>
          <a
            href="https://github.com/siddthecoder"
            target="_blank"
            rel="noreferrer"
            style={{
              fontSize: 11,
              color: isDark ? "#5a9990" : "#6aaba4",
              textDecoration: "none",
              fontWeight: 500,
            }}
          >
            Developed by siddthecoder
          </a>
        </div>
      </div>
    </footer>
  );
}

/* ─────────────────────── SHARED ATOMS ─────────────────────── */
function SectionLabel({
  label,
  color = "#1f766e",
}: {
  label: string;
  color?: string;
}) {
  return (
    <div
      style={{
        display: "flex",
        justifyContent: "center",
        marginBottom: "1rem",
      }}
    >
      <span
        style={{
          fontSize: 11.5,
          fontWeight: 800,
          color,
          letterSpacing: "0.14em",
          textTransform: "uppercase",
          background: `${color}12`,
          padding: "0.3rem 1rem",
          borderRadius: 100,
          border: `1px solid ${color}28`,
        }}
      >
        {label}
      </span>
    </div>
  );
}

function FeatureCard({
  Icon,
  title,
  desc,
  isDark,
  delay,
  visible,
  compact,
}: {
  Icon: React.ElementType;
  title: string;
  desc: string;
  isDark: boolean;
  delay: number;
  visible: boolean;
  compact?: boolean;
}) {
  const [hovered, setHovered] = useState(false);
  return (
    <div
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
      style={{
        ...glassCard(isDark),
        opacity: visible ? 1 : 0,
        transform: visible ? "translateY(0)" : "translateY(24px)",
        transition: `all 0.5s ${delay}s`,
        outline: hovered
          ? "1.5px solid rgba(31,118,110,0.4)"
          : "1.5px solid transparent",
        display: compact ? "flex" : "block",
        gap: compact ? 14 : 0,
        alignItems: compact ? "flex-start" : undefined,
      }}
    >
      <div
        style={{
          width: 40,
          height: 40,
          borderRadius: 10,
          background: hovered
            ? "rgba(31,118,110,0.18)"
            : "rgba(31,118,110,0.1)",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          flexShrink: 0,
          marginBottom: compact ? 0 : 14,
          transition: "background 0.2s",
        }}
      >
        <Icon size={18} color="#1f766e" />
      </div>
      <div>
        <h3
          style={{
            fontSize: compact ? 14 : 15.5,
            fontWeight: 700,
            color: isDark ? "#c8e6e2" : "#0a2e2a",
            margin: "0 0 6px",
            letterSpacing: "-0.02em",
          }}
        >
          {title}
        </h3>
        <p
          style={{
            fontSize: 13.5,
            lineHeight: 1.6,
            color: isDark ? "#6aaba4" : "#4a7a74",
            margin: 0,
          }}
        >
          {desc}
        </p>
      </div>
    </div>
  );
}

/* ─────────────────────── STYLE HELPERS ─────────────────────── */
function glassCard(isDark: boolean): React.CSSProperties {
  return {
    borderRadius: 16,
    border: `1px solid rgba(31,118,110,${isDark ? "0.22" : "0.16"})`,
    background: isDark ? "rgba(15,35,30,0.7)" : "rgba(255,255,255,0.8)",
    backdropFilter: "blur(16px)",
    padding: "20px 22px",
    boxShadow: `0 4px 24px rgba(0,0,0,${isDark ? "0.2" : "0.05"})`,
    transition: "all 0.25s ease",
  };
}

function headingStyle(isDark: boolean): React.CSSProperties {
  return {
    fontSize: "clamp(1.7rem,3.5vw,2.4rem)",
    fontWeight: 800,
    letterSpacing: "-0.04em",
    color: isDark ? "#e8f5f3" : "#0a2e2a",
    textAlign: "center",
    margin: "0 0 1rem",
  };
}

function subStyle(isDark: boolean): React.CSSProperties {
  return {
    fontSize: "clamp(0.95rem,1.8vw,1.1rem)",
    color: isDark ? "#7fb8b2" : "#3d6b64",
    textAlign: "center",
    lineHeight: 1.7,
    margin: "0 auto 0",
    maxWidth: 580,
  };
}

/* ─────────────────────── ROOT EXPORT ─────────────────────── */
export function PublicLanding() {
  const { resolvedTheme } = useTheme();
  const isDark = resolvedTheme === "dark";

  return (
    <div
      style={{
        minHeight: "100vh",
        scrollBehavior: "smooth",
        background: isDark ? "#081412" : "#f8fcfb",
        color: isDark ? "#e8f5f3" : "#0a2e2a",
      }}
    >
      <LandingStyles />
      <Nav />
      <main>
        <Hero isDark={isDark} />
        <StatsBar isDark={isDark} />
        <HowItWorks isDark={isDark} />
        <ForStudents isDark={isDark} />
        <ForTeachers isDark={isDark} />
        <QuizPortal isDark={isDark} />
        <CourseLibrary isDark={isDark} />
        <Comparison isDark={isDark} />
        <CTASection isDark={isDark} />
      </main>
      <Footer isDark={isDark} />
    </div>
  );
}
